### ISSUE TITLE
Post source for the blank keyball

### ISSUE THREAD

**Issue by cculpepper** [settinger/selectric_typeballs#1]
Hello! This is a fantastic project, thank you!

Could you post the source for the blank typeball? Particularly, it looks like the hole is too small, and rotation locking peg is too large for the print (Granted both of these could be my print or my cleanup, but maybe not!)

I'd use the "parent" project, but you say you made a bunch of changes to it, and I'd rather not edit the .stl if possible. 

Thank you!
Chris

**Comment by settinger** [comment]
Hi hello I have not forgotten about this! I am (figuratively) juggling too many things but you are absolutely right that the .scad file for the blank ball needs to be added soon!

**Comment by Hubcapp** [comment]
Confirmed the hole is too small to fit.

**Comment by settinger** [comment]
The typeball SCAD source is included now, apologies again for not providing that sooner.

A couple people started to make excellent improvements of their own; I will try reaching out to get a more useful, more developed typeball generator available to everyone, but it's would most likely be a separate project somewhere else, not in this repo. I'm struggling to find a reason to maintain this version of the typeball generator, especially since I still can't find a functional Selectric to validate parts on.
